spring:
  application:
    name: thirdpaty
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t5gAM5Mihiti8KNTwBY
      secret-key: v0Tz5kI4iWi5Un51Wh0VOrrdZ675gk
      oss:
        endpoint: oss-cn-zhangjiakou.aliyuncs.com
        bucket: u-mall-bearbrick0
server:
  port: 8086
